name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '53 1 * * *' # *-*-* 01:53:00 UTC

permissions:
  contents: read

env:
  RUST_BACKTRACE: full
  # Workaround: https://github.com/rust-lang/rust/issues/113436
  RUSTFLAGS: -Dwarnings -Aimproper-ctypes-definitions

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Enable type layout randomization
        run: echo RUSTFLAGS=${RUSTFLAGS}\ -Zrandomize-layout >> $GITHUB_ENV
        if: matrix.rust == 'nightly'

      - run: cargo test --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo clippy --workspace --tests -- -Dclippy::all

  miri:
    name: Miri
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri

      # Miri is only run on the main crate.
      # Workaround: `abi_stable` is disabled. It breaks rustc now.
      # See https://github.com/rust-lang/rust/issues/113900
      - run: cargo miri test
        env:
          MIRIFLAGS: -Zmiri-strict-provenance

  minimal:
    name: MSRV
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.56
      - run: cargo +nightly generate-lockfile -Z minimal-versions
      - run: cargo check --locked
