name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '53 1 * * *' # *-*-* 01:53:00 UTC

permissions:
  contents: read

env:
  RUST_BACKTRACE: full
  # Workaround: https://github.com/rust-lang/rust/issues/113436
  RUSTFLAGS: -Dwarnings -Aimproper-ctypes-definitions

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable, "1.56"]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo clippy --workspace --tests -- -Dclippy::all -Dclippy::pedantic

  miri:
    name: Miri
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@miri
      # Miri is only run on the main crate.
      - run: cargo miri test --all-features
        env:
          MIRIFLAGS: -Zmiri-strict-provenance
